### ISSUE TITLE
Random Reboots

### ISSUE THREAD

**Issue by ArcherN9** [darknightmare/android_device_xiaomi_armani#8]
I've been experiencing random reboots on R9. (20141116). I haven't been able to pin point when does it exactly happen. ... sometimes, it happens when idle.. other, when I'm typing.

**Comment by younes0** [comment]
I don't encounter this...to get the log after the crash : http://android-revolution-hd.blogspot.fr/2014/02/how-to-generate-kernel-log-after-random.html
